### ISSUE TITLE
Deepmass fails after a few seconds

### ISSUE THREAD

**Issue by Arthfael** [verilylifesciences/deepmass#4]
Hi,

I am trying to run deepmass but am running into the following error (here shown if running tensorflow from a virtual environment, however this also happens if running from a system install):

```
(virtualenv) (base) C:\Windows\system32>python C:/deepmass/prism/preprocess.py --input_data="$D:/test/DeepMass_training_set.csv" --output_data_dir="$D:/test/" --sequence_col="ModifiedSequence" --charge_col="Charge" --fragmentation_col="Fragmentation" --analyzer_col="MassAnalyzer"
D:\virtualenv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\virtualenv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\virtualenv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\virtualenv\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\virtualenv\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\virtualenv\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING: Logging before flag parsing goes to stderr.
W0822 10:06:17.272155 16200 deprecation_wrapper.py:119] From C:/deepmass/prism/preprocess.py:281: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0822 10:06:17.284151 16200 deprecation_wrapper.py:119] From C:/deepmass/prism/preprocess.py:254: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "C:/deepmass/prism/preprocess.py", line 281, in <module>
    app.run(main)
  File "D:\virtualenv\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "D:\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:/deepmass/prism/preprocess.py", line 255, in main
    input_data = pd.read_csv(inputf, sep=',')
  File "D:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "D:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "D:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "D:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1906, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 733, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 935, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 2122, in pandas._libs.parsers.raise_parser_error
TypeError: raise: exception class must be a subclass of BaseException
```

I have Windows Server 2019 Standard and installed all of the requirements. I have tried running the code from a Windows or Anaconda command prompt, with the same error. Any idea what might be happening?

**Comment by petercim** [comment]
Hm, seems like you get a failure at the input reading step during preprocessing. Do you mind pasting a few lines of your input table?

Best,
Peter

**Comment by Arthfael** [comment]
Certainly, my file looks like this in Notepad++:
ModifiedSequence,Charge,Fragmentation,MassAnalyzer
(ac)AAAAAAGAASGLPGPVAQGLK,2,HCD,FTMS
(ac)AAAAAAGAASGLPGPVAQGLKEALVDTLTGILSPVQEVR,4,HCD,FTMS
(ac)AAAAAATAAAAASIR,2,HCD,FTMS
AAAFEQLQK,2,HCD,FTMS
AAAFQHLLLLVGIHLLK,4,HCD,FTMS
AAAFQHLLLLVGIHLLK,3,HCD,FTMS
AAAGLTVALMPVLNQVAGLLGSGEGGLTESWAEAVR,4,HCD,FTMS
...

It was created from the evidence.txt from MaxQuant through a few R code
lines:
# Load
ev <- read.delim("evidence.txt")
# Filter
W <- colnames(ev)[which(toupper(colnames(ev)) %in% c("CONTAMINANT",
"POTENTIAL.CONTAMINANT"))]
for (w in W) { ev <- ev[which((ev[[w]] != "+")|(is.na(ev[[w]]))),] }
ev <- ev[which((ev$Reverse != "+")|(is.na(ev$Reverse))),]
ev <- ev[which((!is.na(ev$Intensity, 2))&(ev$Intensity > 0)),]
# Create peptidoforms table
mod.pep <- apply(ev[, c("Modified.sequence", "Charge")], 1, paste, collapse
= "_-_")
mod.pep <- as.data.frame(t(sapply(strsplit(mod.pep, "_-_"), unlist)))
colnames(mod.pep) <- c("ModifiedSequence", "Charge")
mod.pep$ModifiedSequence <- gsub("^_|_$", "", mod.pep$ModifiedSequence) #
Is this necessary? There are no underscores in the example file
mod.pep$Fragmentation <- "HCD"
mod.pep$MassAnalyzer <- "FTMS"
write.csv(mod.pep, "DeepMass_training_set.csv", row.names = FALSE, quote =
FALSE)

I do not see any inconsistency with the example file shown on the deepmass
page? In my original example my table entries were surrounded by quotes,
but removing them I get the same error.
Best regards,

Armel

**Comment by Arthfael** [comment]
(I should add that I also tested removing the modified peptides altogether
in case they are causing the issue, but still get the same problem)

**Comment by Arthfael** [comment]
Sorry for the reminder, but any idea why this is failing?

**Comment by Shivanitiwary** [comment]
I am sorry but I could not reproduce the error. It works fine for me. I used Anaconda command prompt to run the preprocess.py. It has Python 3.7.4, Tensorflow 1.14.0.

**Comment by Arthfael** [comment]
I have attached an updated training set, in case you want to test my whole
input. It's slightly different from last time, as I made sure all potential
issues were excluded, but it still causes the same error. Issues I
addressed are:
- I checked that I have only the 20 classic amino acids (this was already
the case)
- I made sure to remove any peptide with PTMs other than Methionine
Oxidation, the latter which is displayed as "...M(ox)"
- I removed any potential duplicate lines
Best,

Armel

**Comment by Shivanitiwary** [comment]
I can not find the attachment. I can test it using your input file.

**Comment by Arthfael** [comment]
Ok, somehow, even though I haven't changed anything obvious, things seem to
be working today.

**Comment by Arthfael** [comment]
Thanks for your help.
